---
apiVersion: v1
kind: Namespace
metadata:
  name: teamA
  cluster: local
  labels:
    description: Team A
    ldap-group: LDAP-TEAM-A-OPS
spec:
  kafkaUser: sa-team-a
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: myTopicAcl
  namespace: teamA
spec:
  resourceType: TOPIC
  resource: teamA-
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: teamA
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: myGroupAcl
  namespace: teamA
spec:
  resourceType: GROUP
  resource: teamA-
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: teamA
---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: myConnectAcl
  namespace: teamA
spec:
  resourceType: CONNECT
  resource: teamA-
  resourcePatternType: PREFIXED
  permission: OWNER
  grantedTo: teamA