name: Execute Changes
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: conduktor/conduktor-ctl
    steps:
      - uses: actions/checkout@v3
      - run: conduktor apply -f teams/
        env:
          CDK_BASE_URL: http://34.140.204.135:8079/
          CDK_TOKEN: ${{ secrets.CONDUKTOR_TOKEN }}